
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

-- Table structure for table `#__ra_areas`
--
DROP TABLE IF EXISTS `#__ra_areas`;
CREATE TABLE `#__ra_areas` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `nation_id` int NOT NULL DEFAULT '1',
  `code` varchar(2) NOT NULL,
  `title` varchar(100) NOT NULL,
  `name` varchar(100) NOT NULL,
  `details` mediumtext NOT NULL,
  `hosted` varchar(1) NOT NULL DEFAULT 'N',
  `website` varchar(150) NOT NULL,
  `co_url` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `latitude` decimal(10,8) NOT NULL,
  `longitude` decimal(10,8) NOT NULL,
UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `#__ra_areas`
--

INSERT INTO `#__ra_areas` (`id`, `nation_id`, `code`, `title`, `name`, `details`, `hosted`, `website`, `co_url`, `latitude`, `longitude`) VALUES
(2, 1, 'BF', '', 'Bedfordshire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walk', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/bedfordshire.aspx', '0.00000000', '0.00000000'),
(3, 1, 'BK', '', 'Berkshire', 'We have 9 Berkshire Area groups: 7 traditional groups covering the county; a 20s & 30s group and a flexi group – something for everybody!', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/berkshire.aspx', '0.00000000', '0.00000000'),
(4, 1, 'BU', '', 'Buckinghamshire, Milton Keynes and West Middlesex', 'Supporting the work of the ten groups in the Buckinghamshire, Milton Keynes and West Middlesex Area.', 'N', 'www.bucks-wmiddx-ramblers.org.uk/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/buckinghamshire-milton-keynes-and-west-middlesex.aspx', '0.00000000', '0.00000000'),
(5, 1, 'CB', '', 'Cambridgeshire & Peterborough', '', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/cambridgeshire--peterborough.aspx', '0.00000000', '0.00000000'),
(6, 1, 'CH', '', 'Cheshire East', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/cheshire-east.aspx', '0.00000000', '0.00000000'),
(7, 1, 'CL', '', 'Cornwall', 'Welcome to our Cornwall Ramblers page!  We cover a large area with diverse walking, from coastal, to countryside, exploring industrial mining areas and discovering parish paths and some hidden gems...', 'N', 'www.facebook.com/CornwallRamblers/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/cornwall.aspx', '0.00000000', '0.00000000'),
(8, 1, 'DE', '', 'Derbyshire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'derbyshireramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/derbyshire.aspx', '0.00000000', '0.00000000'),
(9, 1, 'DN', '', 'Devon', 'Walking in Devon you will enjoy both Dartmoor and Exmoor National Parks; The Southwest Way long distance Coastal Path; ( over 630 miles long) The Two Moors Way; The Tarka Trail and much more.', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/devon.aspx', '0.00000000', '0.00000000'),
(10, 1, 'DT', '', 'Dorset', 'For information about Dorset Groups, group contacts and a variety of other topics for walkers in Dorset see our web site www.dorset-ramblers.org.uk', 'N', 'www.dorset-ramblers.org.uk/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/dorset.aspx', '0.00000000', '0.00000000'),
(11, 1, 'ER', '', 'East Yorkshire & Derwent', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'eastyorkshireramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/east-yorkshire-and-derwent.aspx', '0.00000000', '0.00000000'),
(12, 1, 'ES', '', 'Essex', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'essexarearamblers.co.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/essex.aspx', '0.00000000', '0.00000000'),
(13, 1, 'GR', '', 'Gloucestershire', 'Gloucestershire Rambers Area organises a mid-week walks programme of 10-12 mile day walks anywhere in the county & occasionally in neighbouring counties. See also the seven Groups in Gloucestershire.', 'Y', 'gloucestershireramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/gloucestershire.aspx', '0.00000000', '0.00000000'),
(14, 1, 'MR', '', 'Greater Manchester & High Peak', 'Unlike many other Ramblers Areas, Manchester and High Peak itself organises a full led walks programme covering Greater Manchester and beyond, with all walks making use of public transport connections.', 'N', 'manchester-ramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/greater-manchester-and-high-peak.aspx', '0.00000000', '0.00000000'),
(15, 1, 'WX', '', 'Hampshire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'hampshireramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/hampshire.aspx', '0.00000000', '0.00000000'),
(16, 1, 'HW', '', 'Herefordshire', 'The Herefordshire area helps to look after the paths and green spaces throughout the county. We are a leading voice on walking matters in the county.', 'Y', 'herefordshiretrail.com', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/herefordshire.aspx', '0.00000000', '0.00000000'),
(17, 1, 'HF', '', 'Hertfordshire & North Middlesex', 'We support the work of the groups in our Area, including seven geographic and two age-related groups. We work to protect and enhance the Rights of Way in Hertfordshire, Barnet, Enfield and Haringey.', 'N', 'www.ramblers.org.uk/hertfordshire-north-middlesex', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/hertfordshire--north-middlesex.aspx', '0.00000000', '0.00000000'),
(18, 1, 'IL', '', 'Inner London', 'Welcome to the Inner London Area Ramblers. \r\n\r\nOur area has 10 walking groups, three London-wide, and seven based in two or three boroughs, stretching from Heathrow to Thamesmead.', 'Y', 'londonramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/inner-london.aspx', '0.00000000', '0.00000000'),
(19, 1, 'IW', '', 'Isle of Wight', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', 'www.iowramblers.com/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/isle-of-wight.aspx', '0.00000000', '0.00000000'),
(20, 1, 'KT', '', 'Kent', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', 'www.kentramblers.org.uk/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/kent.aspx', '0.00000000', '0.00000000'),
(21, 1, 'LD', '', 'Lake District', 'Covers the whole of Cumbria and the Lancaster area.', 'Y', 'lakedistrictramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/lake-district.aspx', '0.00000000', '0.00000000'),
(22, 1, 'LE', '', 'Leicestershire & Rutland', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'leicsra.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/leicestershire-and-rutland.aspx', '0.00000000', '0.00000000'),
(23, 1, 'LI', '', 'Lincolnshire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'lincolnshireramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/lincolnshire.aspx', '0.00000000', '0.00000000'),
(24, 1, 'LL', '', 'Merseyside and West Cheshire', '', 'N', 'www.ramblers.org.uk/merseyside-west-cheshire', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/merseyside-and-west-cheshire.aspx', '0.00000000', '0.00000000'),
(25, 1, 'ML', '', 'Mid Lancashire', 'Mid Lancashire Ramblers offers a wide range of walks from its groups.  For more details see below or explore the Mid Lancs own web site.', 'Y', 'lancashire-ramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/mid-lancashire.aspx', '0.00000000', '0.00000000'),
(26, 1, 'NR', '', 'Norfolk', 'A dynamic area of nine groups one being a younger age group and a Short and Leisurely sub-group. All of the Area/Group walks are published together on our website and the RA Walks Database. Every member receives a 4 monthly newsletter with all the ...', 'N', 'www.norfolkra.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/norfolk.aspx', '0.00000000', '0.00000000'),
(27, 1, 'MC', '', 'North and Mid Cheshire', 'We organise walks to suit all abilities, using car, coach and public transport. <b>When dogs are allowed on our walks they are usually on a lead. Contact the leader if this concerns you.</b>', 'Y', 'nmc-ramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/north-and-mid-cheshire.aspx', '0.00000000', '0.00000000'),
(28, 1, 'LN', '', 'North East Lancashire', 'Covers Pennine Lancashire - Ribble Valley,  Burnley and Pendle, Rossendale, Blackburn with Darwen and Hyndburn.', 'N', 'www.coach-rambles.org.uk/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/north-east-lancashire.aspx', '0.00000000', '0.00000000'),
(29, 1, 'NY', '', 'North Yorks & South Durham', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/north-yorks--south-durham.aspx', '0.00000000', '0.00000000'),
(30, 1, 'NP', '', 'Northamptonshire', 'The Area consists of 5 Groups, each aiming to promote walking, arrange locally led walks and protect our rights of way. We also organise campaigning events, rallies and promotional events.', 'N', 'northantsramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/northamptonshire.aspx', '0.00000000', '0.00000000'),
(31, 1, 'NN', '', 'Northumbria', '', 'N', 'northumbriaramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/northumbria.aspx', '0.00000000', '0.00000000'),
(32, 1, 'NE', '', 'Nottinghamshire', 'Our footpaths and bridleways span a varied countryside taking in farmland, canals, rivers, fine villages and woodland. Visit our website for more information – www.nottsarearamblers.org.uk', 'Y', 'nottsarearamblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/nottinghamshire.aspx', '0.00000000', '0.00000000'),
(33, 1, 'OX', '', 'Oxfordshire', 'Our 10 groups help local people enjoy walking in good company with 1000 walks each year, many of which are short and leisurely paced, led by local experts. So, boost your health and happiness with us.', 'Y', 'ramblers-oxon.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/oxfordshire.aspx', '0.00000000', '0.00000000'),
(34, 1, 'SS', '', 'Shropshire', 'Shropshire is a diverse county, offering walks in landscapes ranging from the rugged hills of the south to the special landscape of the Meres and Mosses in the north.', 'Y', 'shropshireramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/shropshire.aspx', '0.00000000', '0.00000000'),
(35, 1, 'SO', '', 'Somerset', 'This Area organises a regular programme of walks for families.', 'Y', 'somersetramblers.co.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/somerset.aspx', '0.00000000', '0.00000000'),
(36, 1, 'SD', '', 'South Yorks & N.E.Derbyshire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', 'www.synedramblers.btck.co.uk/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/south-yorks-and-nederbyshire.aspx', '0.00000000', '0.00000000'),
(38, 1, 'SK', '', 'Suffolk', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'suffolkramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/suffolk.aspx', '0.00000000', '0.00000000'),
(39, 1, 'SR', '', 'Surrey', 'Visit the Surrey Area website for details of our 17 walking groups covering the county of Surrey and the London boroughs of Croydon, Kingston, Merton, Richmond and Sutton.', 'Y', 'surreyramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/surrey.aspx', '0.00000000', '0.00000000'),
(40, 1, 'SX', '', 'Sussex', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'sussexramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/sussex.aspx', '0.00000000', '0.00000000'),
(41, 1, 'WK', '', 'Warwickshire', 'Welcome to our beautiful county in The Heart Of England!', 'N', 'www.warwickshireramblers.org.uk/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/warwickshire.aspx', '0.00000000', '0.00000000'),
(42, 1, 'WR', '', 'West Riding', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', 'ramblersyorkshire.org/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/west-riding.aspx', '0.00000000', '0.00000000'),
(43, 1, 'WE', '', 'Wiltshire & Swindon', 'The Wiltshire Ramblers currently total some 1,550 members divided into 6 groups, one of which is our young persons group for 20 to 40 year olds. Our groups work towards the charitable aims of Ramblers in different ways, but one thing they all do is ...', 'Y', 'wiltsswindonramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/wiltshire--swindon.aspx', '0.00000000', '0.00000000'),
(44, 1, 'WO', '', 'Worcestershire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'worcestershireramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/worcestershire.aspx', '0.00000000', '0.00000000'),
(45, 2, 'CY', '', 'Clydesdale to Solway', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/clydesdale-to-solway.aspx', '0.00000000', '0.00000000'),
(46, 2, 'CF', '', 'Forth Valley, Fife & Tayside', 'Forth Valley, Fife and Tayside Area extends a warm welcome to all new walkers, visitors and guests. You can walk with any of our 13 groups, just choose a walk that suits and get in touch!', 'Y', 'fvft-ramblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/forth-valley-fife--tayside.aspx', '0.00000000', '0.00000000'),
(47, 2, 'GP', '', 'Grampian', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/grampian.aspx', '0.00000000', '0.00000000'),
(48, 2, 'SC', '', 'Highland & Islands', 'The Highlands is one of Europe’s most unspoilt scenic regions, a rugged landscape of imposing mountains, sheltered fertile glens and scattered offshore islands offering unsurpassed walking for all.', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/highland--islands.aspx', '0.00000000', '0.00000000'),
(49, 2, 'LB', '', 'Lothian & Borders', 'There are eleven Groups in the Lothian and Borders Ramblers Area, each arranges a walks programme suitable for people with different levels of experience and fitness.  ', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/lothian--borders.aspx', '0.00000000', '0.00000000'),
(50, 2, 'SL', '', 'North Strathclyde', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'D', 'northstrathclyderamblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/north-strathclyde.aspx', '0.00000000', '0.00000000'),
(51, 2, 'RB', '', 'Renfrewshire, Cowal & Bute', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'rcbarearamblers.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/renfrewshire-cowal-and-bute.aspx', '0.00000000', '0.00000000'),
(52, 2, 'WS', '', 'South West Scotland', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/south-west-scotland.aspx', '0.00000000', '0.00000000'),
(53, 3, 'CA', '', 'Carmarthenshire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/carmarthenshire.aspx', '0.00000000', '0.00000000'),
(54, 3, 'CE', '', 'Ceredigion', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', 'www.ceredigionramblers.org.uk/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/ceredigion.aspx', '0.00000000', '0.00000000'),
(55, 3, 'SW', '', 'Glamorgan', 'We work with our Groups protecting/enhancing footpaths & countryside; and creating opportunities to enjoy the outdoors through led walks. ', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/glamorgan.aspx', '0.00000000', '0.00000000'),
(56, 3, 'GG', '', 'Greater Gwent', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/greater-gwent.aspx', '0.00000000', '0.00000000'),
(57, 3, 'LW', '', 'North Wales', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'Y', 'ramblersnorthwales.org.uk', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/north-wales.aspx', '0.00000000', '0.00000000'),
(58, 3, 'PE', '', 'Pembrokeshire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', 'www.pembrokeshireramblers.org.uk/', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/pembrokeshire.aspx', '0.00000000', '0.00000000'),
(59, 3, 'MW', '', 'Powys', 'For details of Rail Rambles (walk info; contacts; history) in mid Wales and the Marches, refer railrambles.', 'N', 'www.ramblers.org.uk/powys', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/powys.aspx', '0.00000000', '0.00000000'),
(60, 1, 'AV', '', 'Avon', 'This Area covers most of the former County of Avon.', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/avon.aspx', '0.00000000', '0.00000000'),
(66, 1, 'NS', '', 'Staffordshire', 'Our areas help local people enjoy walking and protect the places we all love to walk. Areas help look after paths and green spaces, open up new places to explore and act as the leading voice on walking matters near you. They also support our local ...', 'N', '', 'https://www.ramblers.org.uk/go-walking/group-finder/areas/staffordshire.aspx', '0.00000000', '0.00000000');

--
-- Indexes for table `#__ra_areas`
--
ALTER TABLE `#__ra_areas`
  ADD PRIMARY KEY (`id`);

# ALTER TABLE `#__ra_areas`
#     ADD CONSTRAINT fk_areas_nation_id,
#     FOREIGN KEY (nation_id) 
#        REFERENCES `#__nations`(id); 
--
-- AUTO_INCREMENT for table `#__ra_areas`
--
ALTER TABLE `#__ra_areas`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=67;
# ------------------------------------------------------------------------------
