/**
 * @version     CVS: 1.0.6
 * @package     com_ra_tools
 * @copyright   2023 Charlie Bigley
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Charlie Bigley <webmaster@bigley.me.uk>
 * 
 * Dummy version as generated by component-generator
 */


